CREATE TABLE "balance" (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    "timestamp" TIMESTAMP NOT NULL,
    CONSTRAINT BALANCE_FK FOREIGN KEY (user_id) REFERENCES "user" (ID)
);